// flow-typed signature: 04e971821528ee656da22b6713610aa5
// flow-typed version: <<STUB>>/react-travel_v^1.3.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-travel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-travel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-travel/dist/react-travel' {
  declare module.exports: any;
}

declare module 'react-travel/dist/react-travel.min' {
  declare module.exports: any;
}

declare module 'react-travel/lib/react-travel' {
  declare module.exports: any;
}

declare module 'react-travel/lib/Travel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-travel/dist/react-travel.js' {
  declare module.exports: $Exports<'react-travel/dist/react-travel'>;
}
declare module 'react-travel/dist/react-travel.min.js' {
  declare module.exports: $Exports<'react-travel/dist/react-travel.min'>;
}
declare module 'react-travel/lib/react-travel.js' {
  declare module.exports: $Exports<'react-travel/lib/react-travel'>;
}
declare module 'react-travel/lib/Travel.js' {
  declare module.exports: $Exports<'react-travel/lib/Travel'>;
}
